publiclab/Leaflet.DistortableImage

DistortableImage.js
src/edit/DistortableImage.Edit.js
src/edit/DistortableImage.EditToolbar.js

I made some important changes to the Leaflet.Toolbar API.  This PR refactors the DistortableImage editing toolbar to accomodate these changes.

Update DistortableImage.EditToolbar to ccomodate changes to the leaflet-toolbar API.

---

README.md

last few README additions

---

dist/leaflet.distortableimage.js
src/util/DomUtil.js

added L.Browser.ie3d for Explorer 10+, karma tests passing

---

package.json

Would like to be able to use this with webpack etc.

Add main to package.json so require() works

---

package.json

Update package.json to be compliant with npm naming https://docs.npmjs.com/files/package.json

Update package.json 

---

examples/index.html
package.json

fixes #73 eliminates bower_components deps

change back to node modules

---

package.json

update to jquery 3

---

dist/leaflet.distortableimage.js
package.json
src/DistortableImageOverlay.js

For integration with https://github.com/publiclab/image-sequencer/
https://leafletjs.com/reference-1.3.0.html#imageoverlay-crossorigin

Crossorigin option for CORS access to pixels

---

dist/leaflet.distortableimage.js
package.json
src/DistortableImageOverlay.js

capitaliZation

---

Gruntfile.js
dist/leaflet.distortableimage.js
package-lock.json
src/edit/DistortableImage.Edit.js
test/karma.conf.js

Fixes #126's #84 
/cc @jywarren

Clicked-on images are brought to front

---

src/edit/DistortableImage.Edit.js

Add key binding for 'delete'

---

test/src/edit/DistortableImageEditSpec.js
test/src/edit/RotateAndScaleHandleSpec.js
test/src/edit/RotateHandleSpec.js
test/src/edit/ScaleHandleSpec.js

Update tests in edit folder to correct class factory syntax

issue:189 Update tests in edit folder to correct class factory syntax

---

test/src/DistortableCollectionSpec.js
test/src/DistortableImageOverlaySpec.js

Closes #190. Re-done after creating new branch from `main` instead of `master`.

Update remaining tests to correct class factory syntax

---

test/src/DistortableCollectionSpec.js
test/src/DistortableImageOverlaySpec.js

Tests updated to use class factory syntax

---

test/SpecHelper.js
test/src/DistortableCollectionSpec.js

Introduce chai global utilities

---

test/src/edit/DistortableImageEditSpec.js
test/src/edit/RotateAndScaleHandleSpec.js
test/src/edit/RotateHandleSpec.js
test/src/edit/ScaleHandleSpec.js

Fixes #198  (<=== Add issue number here)
Thanks!

removed the new keyword and change D to d

---

dist/leaflet.distortableimage.js
src/edit/DistortableImage.Edit.js

Undefined `call` condition

---

test/src/DistortableImageOverlaySpec.js
test/src/edit/DistortableImageEditSpec.js

Fixes Issue #249 
Removed the `new `keyword from the code blocks and updated `L.LatLng` to` L.latLng` 
@sashadev-sky

Updated Keywords

---

src/edit/DistortableImage.Edit.js

Fixes #284 
Issue creator: @sashadev-sky

Update L.LayerGroup to class factory syntax#284

---

.github/ISSUE_TEMPLATE/--bug-report.md

Updates to the bug-report template after trying it initially

Update issue templates

---

.github/ISSUE_TEMPLATE/--feature-request.md

Initial PR to add a feature request template to the available issues templates

Add feature template

---

.github/ISSUE_TEMPLATE/--help-with-leaflet-distortableimage.md

initial PR to create a help issue template (for asking questions, requesting documentation / API improvements, etc.)

Create a help issue template

---

.github/ISSUE_TEMPLATE/--bug-report.md
.github/ISSUE_TEMPLATE/--feature-request.md
.github/ISSUE_TEMPLATE/--help-with-leaflet-distortableimage.md

- Added space where required 
- Labels changed
Thanks!

Issue templates updated

---

dist/leaflet.distortableimage.js
src/DistortableImageOverlay.js
src/edit/BoxSelectHandle.js
src/edit/DistortableImage.Edit.js

Use class factory for Point

---

package-lock.json
package.json

Fixes #https://github.com/publiclab/mapknitter/issues/124#issuecomment-501893548 (<=== Add issue number here)
Thanks!

bump 0.4.3 to 0.4.4

---

dist/leaflet.distortableimage.js
package.json
src/DistortableCollection.js

re #314 and https://github.com/publiclab/mapknitter/pull/782

fix for cache bust in multi export

---

dist/leaflet.distortableimage.js
package.json
src/DistortableCollection.js

From https://github.com/publiclab/mapknitter/pull/782

better response handling

---

dist/leaflet.distortableimage.js
package.json
src/DistortableImageOverlay.js
src/edit/RotateScaleHandle.js

fix for scaling issues 

---

dist/leaflet.distortableimage.js
src/DistortableImageOverlay.js

Fixes #354  (<=== Add issue number here)
Thanks!

Appending Image using getPane() method

---

README.md
dist/leaflet.distortableimage.css
dist/leaflet.distortableimage.js
examples/index.html
examples/listeners.html
examples/select.html
package-lock.json
package.json
src/DistortableCollection.js
src/DistortableImageOverlay.js
src/edit/DistortableImage.Edit.js

Fixes #330  (<=== Add issue number here)
Thanks!

Update css selector scope so that classes are added internally

---

dist/leaflet.distortableimage.js
package-lock.json
package.json
src/DistortableImageOverlay.js

hotfix remove unused options line (MK complaining about it)

---

README.md

Adding this badge because its nice and mainly because my travis build keeps failing for #243 and im trying to see if a different one will pass
Thanks!

Add contributors welcome badge

---

README.md
dist/leaflet.distortableimage.js
examples/index.html
examples/select.html
package-lock.json
package.json
src/edit/tools/DistortableImage.PopupBar.js

Fixes #373  (<=== Add issue number here)
Thanks!

finish PR add rotate and scale actions #373

---

dist/leaflet.distortableimage.css

Change rgb to rgba

---

README.md
dist/leaflet.distortableimage.js
package-lock.json
package.json
src/DistortableCollection.js
src/DistortableImageOverlay.js
src/edit/DistortableCollection.Edit.js
src/edit/DistortableImage.Edit.js
src/edit/handles/ScaleHandle.js
test/src/DistortableCollectionSpec.js
test/src/DistortableImageOverlaySpec.js
test/src/edit/DistortableCollectionEditSpec.js
test/src/edit/DistortableImageEditSpec.js

Fixes #430  (<=== Add issue number here)
Thanks!

Expose `Select` and `deselect` to API

---

dist/leaflet.distortableimage.js
package.json
src/mapmixins/MapMixins.js
test/src/DistortableImageOverlaySpec.js

fix max zoom

---

dist/leaflet.distortableimage.css

Fixes #382 (<=== Add issue number here)
Thanks!

Disable mouse pointer on disabled images

---

README.md
dist/leaflet.distortableimage.js
src/util/Utils.js

Fixes #0000  (<=== Add issue number here)
Thanks!

Correct tooltip pluralization

---

package-lock.json

Audit package lock

---

src/edit/handles/DragHandle.js

closes issue #602

---

src/util/ImageUtil.js

adding es6 function syntax to ImageUtils.js

---

src/util/IconUtil.js

Fixes #596 (<=== Add issue number here)
Thanks!

Update method creation in L.IconUtil to ES6 syntax

---

src/edit/actions/StackAction.js

L.StackAction method updated to ES6 syntax

---

src/edit/handles/FreeRotateHandle.js

Fixes #612 (<=== Add issue number here)
@sashadev-sky
Thanks!

updated functions to ES6 plus var->let

---

README.md

cc @sashadev-sky - how does this look?
re #649

docs example of how to add add-on tools

---

src/mapmixins/DoubleClickZoom.js

Updating DoubleClickZoom method creation syntax for ES6

---

src/mapmixins/MapMixins.js

Fixes #630 (<=== Add issue number here)
Thanks!

Fixed #630 - MapMixins.js method creation to ES6 syntax

---

src/util/DomUtil.js

Updated L.DomUtil methods to ES6

---

src/edit/DistortableImage.Edit.js

Fixes #719 (<=== Add issue number here)
Thanks!

Update L.DistortableImage.Edit.js function syntax to ES6

---

src/edit/DistortableImage.Edit.js

Fixes #721  (<=== Add issue number here)
Thanks!

Update L.DistortableImage.Edit.js method creation to ES6 syntax IV

---

src/util/Utils.js

Updated L.Utils method creation to ES6 syntax

---

.gitpod.yml
.travis.yml

Follow-up to un-revert Gitpod in #716
Follow-up to #680

re-add GitPod w --no-sandbox headless chrome option

---

src/edit/DistortableImage.Edit.js

Fixes #730  (<=== Add issue number here)
Thanks!

Updated mentioned methods to ES6 syntax VI

---

src/edit/DistortableImage.Edit.js

Fixes #718 (<=== Add issue number here)
https://github.com/publiclab/Leaflet.DistortableImage/issues/718
@sashadev-sky 
Thanks!

Updating L.DistortableImage.Edit.js to ES6 syntax

---

src/components/DistortableImage.Keymapper.js

Fixes #764  (<=== Add issue number here)
* [x ] PR is descriptively titled 📑 and links the original issue above 🔗
* [x ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt test`
* [x ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ x] screenshots/GIFs are attached 📎 in case of UI updates
* [ x] @mention the original creator of the issue in a comment below for help or for a review
Please be …

removed function keyword from 6 function definitions

---

src/edit/DistortableImage.Edit.js

Fixes #736 
(https://github.com/publiclab/Leaflet.DistortableImage/issues/736)
@sashadev-sky Please review this.
Thanks!

Changed syntax to ES6 for 6 functions

---

.github/workflows/build.yml

Setup Github actions for CI

---

examples/archive.html

feat: 🎸 create images sidebar

---

dist/leaflet.distortableimage.js
src/DistortableImageOverlay.js

added exemption for L.CRS.Simple to _cornerExceedsMapLats()
Fixes #1032  (<=== Add issue number here)
Fixes #1007
Thanks!

Add exception to bounds catch for l.crs.simple

---

src/edit/actions/DeleteAction.js

update DeleteAction method creation syntax to ES6

---

src/edit/actions/ExportAction.js

Fixes #1042 (<=== Add issue number here)
Thanks!

Update exportaction.js to have ES6 syntax

---

src/edit/actions/BorderAction.js

Updated method creation syntax to ES6 in BorderAction.js

---

src/edit/actions/DistortAction.js

Fixes #1039  (<=== Add issue number here)
Thanks!

Update method creation syntax to ES6 DistortAction.js

---

src/edit/actions/OpacityAction.js

Update OpacityAction.Js to  ES6 syntax

---

src/edit/actions/LockAction.js

Update method creation syntax to ES6 LookAction.js iamtienng

---

src/edit/actions/GeolocateAction.js

changed some lines of code on the GeolocateAction.js file
Fixes #1044 (<=== Add issue number here)
* [yes ] PR is descriptively titled 📑 and links the original issue above 🔗
* [yes ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt test`
* [ yes] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ no] screenshots/GIFs are attached 📎 in case of UI updates
* [ yes] @mention the original creator of the issue in a comment below for help or for a review
* @first-timers 
> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at …

Updated GeolocateAction.js

---

.github/config.yml

This PR fixes issue #1072 
The file has been edited as requested.
Thanks!

Update config.yml #1072

---

src/iconsets/IconSet.js

fix: fixed error in the file

---

src/DistortableCollection.js

change the syntax to es6
Fixes #1069 (<=== Add issue number here)
@TildaDares 
Thanks!

Updated DistortableCollection.js

---

.github/first-timers-issue-template.md

Fixes #1071 (<=== Add issue number here)
Thanks!

Updated the first timers issue template.

---

examples/archive.html

feat: 🎸 place images in the sidebar onto the map

---

src/edit/handles/LockHandle.js

Updated ES6 LockHandle.js

---

src/mapmixins/BoxCollector.js

Update syntax to ES6 BoxCollector.js

---

src/DistortableImageOverlay.js

Leaflet.DistortableImage changes

---

src/edit/handles/RotateHandle.js

Reverts publiclab/Leaflet.DistortableImage#1089

Revert "Replaced `var` keyword with `const` in RotateHandle.js"

---

src/edit/actions/ExportAction.js

changed var keyword to let/const
Fixes #1086  (<=== Add issue number here)
Thanks!

Update ExportAction.js var keywords

---

src/util/Utils.js

Replaced var keyword with const/let on src/util/Utils.js file

---

src/util/MatrixUtil.js

Proposed changes for var keyword @TildaDares
Thanks!

Replace `var` keyword with `let`/`const`

---

src/edit/handles/DragHandle.js

updated DragHandle.js

---

src/edit/actions/LockAction.js

Update LockAction.js var keywords

---

src/edit/actions/FreeRotateAction.js

feat: Update FreeRotateAction with ES6

---

src/DistortableImageOverlay.js

Update variable declaration

---

src/edit/actions/StackAction.js

Fixes #620  (<=== Add issue number here)
Thanks!

updating file from es5 to es6

---

src/edit/actions/BorderAction.js

Thanks!
@TildaDares 
Please review
Thanks

changed variable declaration from var to let and const

---

src/mapmixins/DoubleClickLabels.js

I changed the variables with var to let.
Thanks!

 Updated DoubleClickLabels.js

---

src/util/IconUtil.js

Update IconUtil.js  change var to const 

---

src/edit/actions/DeleteAction.js

Fixes #1086  (<=== Add issue number here)
Thanks!

changed var to const & let

---

src/util/DomUtil.js

Switching var to let and const

---

index.html

Fixes #1133  (<=== Add issue number here)
* [*] PR is descriptively titled 📑 and links the original issue above 🔗
* [*] code is in uniquely-named feature branch and has no merge conflicts 📁
* [*] screenshots/GIFs are attached 📎 in case of UI updates
* [*] @mention the original creator of the issue in a comment below for help or for a review
Thanks!

Add lang attribute to the html element#1133

---

examples/export.html
examples/index.html
examples/select.html

Fixes #1151  (<=== Add issue number here)
@segun-codes
Thanks!

'var' changed to ES6 'let' keyword

---

dist/leaflet.distortableimage.js
examples/index.html
package-lock.json
package.json

Fixes #998  (<=== Add issue number here)
Thanks!
Screenshot
GIF
https://user-images.githubusercontent.com/59090053/195871681-f7b6d6cb-b05f-4fb0-937a-8849eab4a7bf.mp4

geocoding search box

---

src/edit/toolbars/DistortableImage.PopupBar.js

Replaced var keywords with let or const - / src / edit / toolbars /DistortableImage.PopupBar.js #1086

---

src/edit/handles/LockHandle.js

Replace 'var' keywords with 'const' in lockhandle.js

---

src/mapmixins/DoubleClickZoom.js

Fixes #1204  (<=== Add issue number here)
Thanks!

update 'comments to single line'

---

src/edit/actions/DragAction.js

Fixes #1040(<=== Add issue number here)
@TildaDares.
* [x ] PR is descriptively titled 📑 and links the original issue above 🔗
Thanks!

updated variable declaration and also updated creation method syntax to ES6

---

README.md

Create a new header in the Readme linking to Mapknitter Lite 

---

src/edit/handles/EditHandle.js

Update method creation syntax to ES6 EditHandle.js

---

dist/leaflet.distortableimage.js
examples/archive.html
src/DistortableCollection.js
src/DistortableImageOverlay.js
src/edit/DistortableImage.Edit.js
src/edit/actions/EditAction.js
src/edit/actions/FreeRotateAction.js
src/edit/actions/GeolocateAction.js
src/edit/actions/RestoreAction.js
src/edit/handles/DistortHandle.js
src/edit/handles/DragHandle.js
src/edit/handles/ScaleHandle.js
src/edit/toolbars/DistortableImage.PopupBar.js
src/mapmixins/DoubleClickLabels.js
src/util/MatrixUtil.js

Fixes #1190  (<=== Add issue number here)
Thanks!

When this.options.rotation.deg = 0 default to deg (FTO)

---

README.md
debug/pixelorigin.html
debug/pixelorigin.js
dist/leaflet.distortableimage.js

Fixes #0000 (<=== Add issue number here)#1215
Thanks!

Transfered js codes in pixelorigin.html into a seperate

---

src/edit/actions/ExportAction.js

Removed logical NOT operator where unnecessary and modified code 

---

examples/archive.html

Fixes #1262 (<=== Add issue number here)
Thanks!

Update archive.html to support url correction from http to https

---

examples/local.css
examples/local.html

Based on this comment: https://github.com/publiclab/Leaflet.DistortableImage/pull/1296#issuecomment-1353692787
Implementation of the infoBar toggle button sticking to the side

infoBar fix

---

src/edit/toolbars/DistortableImage.PopupBar.js

Issue 1310 - Change let to const

---

src/util/MatrixUtil.js

Change var to const/let in local.js

---

README.md

Fixes #1326  (<=== Add issue number here)
Thanks!

Corrected the Misspelt word in "README.md"

---

src/DistortableCollection.js

Functionality to Detect JSON in Shareable URL

---

.eslintrc.js
dist/leaflet.distortableimage.js
examples/archive.html
examples/js/archive.js
examples/js/modules/pagination.js
examples/js/modules/paginator.js

sidebar pagination

---

dist/leaflet.distortableimage.js
examples/archive.html
examples/js/archive.js

share map 

---

.github/workflows/build.yml
examples/archive.html
examples/js/archive.js
examples/js/savedMaps.js

compartmentalize archive demo savedMaps into separate module

---

debug/pixelorigin.js

changing from getElementById to querySelector on #1174 issue

---

examples/archive.html

Update archive.html to include link to list of archived MK maps
