publiclab/Leaflet.DistortableImage

examples/select.html

This uses a global images array to manage deselection of other images. It could potentially be rewritten to use Leaflet's map._layers to avoid this, if we wanted to build this function into the plugin itself, or we could leave this example code for folks who want to use this kind of behavior in their application code. @manleyjster, do you have an opinion?

basic selection/deselection

---

bower.json

I am using this plugin in a project that uses bower to install dependencies and then link/compile them in. I had difficulty with this library since some of the dependencies are pulled in via npm and referenced in the example files. In order to successfully get this plugin to build with dependencies via bower, I had to move some of the front end dependencies to a `dependencies` block (since `devDependencies` are not built in by default on production envs).

Added dependency list to bower.json

---

src/util/DomUtil.js

I don't think getRotateString is called from within our source, but this is probably still a good idea.

add gecko3d to getRotateString method for Firefox

---

.travis.yml
Gruntfile.js
package-lock.json
test/karma.conf.js

Fixes #122, re: #126 
**Success logs**
````sh
▶ grunt build
Running "jshint:source" (jshint) task
>> 11 files lint free.
Running "jshint:grunt" (jshint) task
>> 1 file lint free.
Running "karma:development:start" (karma) task
START:
06 02 2019 16:45:54.868:INFO [karma-server]: Karma v3.1.4 server started at http://0.0.0.0:9876/
06 02 2019 16:45:54.870:INFO [launcher]: Launching browsers PhantomJS with concurrency unlimited
06 02 2019 16:45:54.890:INFO [launcher]: Starting browser PhantomJS
06 02 2019 16:45:58.299:INFO [PhantomJS 2.1.1 (Linux 0.0.0)]: Connected on socket LpERJgPzRtZzNKSWAAAA with id 70904612
L.DistortableImageOverlay
#_calculateProjectiveTransform
✖ Should (skipped)
getCenter
✔ Should return the center when the outline of the image is a rectangle.
L.DistortableImage.Edit
✔ …
```

Resume Travis builds and remove karma errors

---

dist/leaflet.distortableimage.js
package-lock.json
package.json
src/edit/DistortableImage.Edit.js

Cleans up #100, and fixes some build errors that appeared after the cleanup.
**JSHint logs**
````sh
Running "jshint:source" (jshint) task
src/edit/DistortableImage.Edit.js
335 |    _toggleExport: function (){
^ Duplicate key '_toggleExport'.
>> 1 error in 11 files
Warning: Task "jshint:source" failed. Use --force to continue.
Aborted due to warnings.
````
**Karma logs**
````sh
Running "karma:development:start" (karma) task
22 02 2019 01:09:54.219:ERROR [config]: Error inconfig file!
TypeError: Path must be a string. Received null
at assertPath (path.js:28:11)
at Object.extname (path.js:1456:5)
at phantomJSExePath (/home/champagnepapi/Desktop/workspace/ldi/node_modules/karma-phantomjs-launcher/index.js:18:12)
at Object.<anonymous> …
```

Fix jshint/karma errors and duplicate code from #100

---

dist/leaflet.distortableimage.js
src/edit/DistortableImage.Edit.js

(Bare with me, this is my first commit :D)
I noticed that the placement of the toolbar was based off a fixed increase:
``map.containerPointToLatLng(new L.Point(point.x,point.y-20));``
This wasn't preferable in certain distortions/positions/rotations so I wrote a script (see commit), that finds the corner with the highest latitude, then uses that as a 'y' position. There was no modification for the logic of 'x', that is still based off the centroid.
I tested the code profusely, it looks better.
I can provide a website to a demo of this edit on request, though it is in development currently so 404's may be expected.
Also interested in any feedback regarding my commit etiquette as this is a new thing for me.

An improvement to the placement of the toolbar.

---

test/SpecHelper.js
test/src/DistortableCollectionSpec.js
test/src/DistortableImageOverlaySpec.js

Fixes #248
Leaflet objects are created without using the new keyword. This is achieved by complementing each class with a lowercase factory method. For this reason:
Removed the `new` keyword from the following code blocks and updated `L.LatLng` to `L.latLng`.

Updated L.LatLng initializers to class factory syntax

---

src/edit/EditHandle.js
src/edit/RotateHandle.js
src/edit/RotateScaleHandle.js
src/edit/ScaleHandle.js

added _calculateAngle to L.EditHandle

---

dist/leaflet.distortableimage.js
package-lock.json
package.json
src/DistortableCollection.js

Fixes as follow-up to #316 #318

Export ordering fix

---

dist/leaflet.distortableimage.js
src/DistortableImageOverlay.js

Fixes #42  (<=== Add issue number here)
- Pulled out from #339 as requested
- Firefox zoom animation was turned off in #42 because of radical distortions in the corners. However, I am now seeing only the same distortions as the ones you find in chrome, so I think zoom animation can be turned back on now! 
- removed conditional part of:
```JS
if (!L.Browser.gecko) {
image.style[L.DomUtil.TRANSFORM] = [translation, warp].join(" ");
}
```
- Should we move forward with this and close #42 on merge? @jywarren  (see gif below)
If tests do fail, click on the …

Fix Firefox Zoom animation

---

dist/leaflet.distortableimage.js
src/edit/DistortableImage.Edit.js

resolve trapezoidal distortion issues with project() instead of .latLngToLayerPoint()

---

README.md
dist/leaflet.distortableimage.js
src/DistortableCollection.js
src/DistortableImageOverlay.js
src/edit/DistortHandle.js
src/edit/DistortableImage.Edit.js
src/edit/RotateHandle.js
src/edit/RotateScaleHandle.js
src/edit/ScaleHandle.js
src/edit/tools/DistortableImage.PopupBar.js
test/SpecHelper.js
test/src/DistortableCollectionSpec.js
test/src/DistortableImageOverlaySpec.js
test/src/edit/DistortableImageEditSpec.js
test/src/edit/EditHandleSpec.js

Testing for #341, testing  scale and exposing scaleBy API
Fixes #352 
- #301 
- #85 
Thanks!
====================
changes
- below moved to L.DistortableImageOverlay:
-  `scaleBy`
- `rotateBy`
- `_revert`: remove distortions using `project`, remaining bug is img shifts position a little on the map. holding off to try to fix completely in smaller PR bc will …

fix scale/rotate/rotateScale distortions + tests

---

dist/leaflet.distortableimage.js
package-lock.json
package.json
src/DistortableCollection.js
src/edit/DistortableCollection.Edit.js
src/edit/tools/DistortableImage.ControlBar.js

Fixes #381  (<=== Add issue number here)
Thanks!

move startExport to DistortableCollection.Edit

---

dist/leaflet.distortableimage.js
package-lock.json
package.json
src/edit/DistortableCollection.Edit.js
src/edit/DistortableImage.Edit.js
src/edit/tools/DistortableImage.ControlBar.js
src/edit/tools/DistortableImage.PopupBar.js

Fixes #376
cc @sashadev-sky  @jywarren 
Thanks!

[WIP] add dynamic-hotkeys functionality

---

test/SpecHelper.js
test/src/DistortableCollectionSpec.js
test/src/edit/DistortableCollectionEditSpec.js
test/src/edit/DistortableImageEditSpec.js

Fixes #410 
* [✅] PR is descriptively titled 📑 and links the original issue above 🔗
* [✅ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt`
* [ ✅] code is in uniquely-named feature branch and has no merge conflicts 📁
* [✅ ] screenshots/GIFs are attached 📎 in case of UI updates - Not applcable
* [✅ ] @mention the original creator of the issue in a comment below for help or for a review
@rexagod 
Adds generic method which takes in the event and provides the corresponding properties where ever required. 
Thanks!

#410 - Add generic method for mouse events simulation.

---

package-lock.json
package.json

- Relocation of jQuery from devDepencies to depencies
Fixes #411
@rexagod @sashadev-sky 
Cheers!

Fix: dependancy types in package.json #411

---

README.md
package.json
src/edit/DistortableImage.Edit.js
test/src/edit/DistortableImageEditSpec.js

Resolves https://github.com/publiclab/Leaflet.DistortableImage/issues/367
@sashadev-sky @rexagod Could you please take a look at this? 
This should cover all four features described in *Part 1*. There were some linting errors that were already present, so I had to commit with `--no-verify` to bypass the pre-commit hook. Perhaps this would be worth fixing in a separate PR? 
I'm not too sure if the tests I added are entirely comprehensive, would appreciate help with that!

Add a `#replaceTool` method

---

README.md
dist/leaflet.distortableimage.js
package-lock.json
package.json
src/edit/DistortableCollection.Edit.js
src/mapmixins/BoxCollector.js

Fixes #466  (<=== Add issue number here)
Thanks!
- allows enabling `boxZoom` instead of `boxCollector` and documents in README
- bumps minor version 0.8.7 -> 0.8.8

Allow swapping between boxZoom and boxCollector

---

dist/leaflet.distortableimage.js
examples/select.html
package-lock.json
package.json
src/edit/DistortableCollection.Edit.js
src/edit/actions/ExportAction.js

In the old UI, the spinner would continue spinning after the images have been
exported. Now it's fixed.
Resolves #470 
@sashadev-sky could you review this, please?

FIX: Remove loading spinner after image export

---

dist/leaflet.distortableimage.js
src/DistortableImageOverlay.js

The [video](https://streamable.com/j1uyf) shows the method in action.
`getAngle()` returns a value in degrees(0 - 360).
Resolves #102 
@keshav234156 @jywarren @rexagod could someone review this?
Thanks.

ADD: getAngle() method

---

dist/leaflet.distortableimage.js
src/DistortableImageOverlay.js

The method accepts an angle in degrees and sets element's rotation to be
that angle. It can also accept negative degrees.
[Demo](https://streamable.com/ydogf)
Resolves #102
@sashadev-sky @jywarren @SidharthBansal could you review this, please?

ADD: setAngle() method

---

README.md
dist/leaflet.distortableimage.js
src/DistortableCollection.js
src/DistortableImageOverlay.js
src/edit/actions/BorderAction.js
src/edit/actions/DeleteAction.js
src/edit/actions/DistortAction.js
src/edit/actions/DragAction.js
src/edit/actions/ExportAction.js
src/edit/actions/FreeRotateAction.js
src/edit/actions/GeolocateAction.js
src/edit/actions/LockAction.js
src/edit/actions/OpacityAction.js
src/edit/actions/RevertAction.js
src/edit/actions/RotateAction.js
src/edit/actions/ScaleAction.js
src/edit/actions/StackAction.js
src/edit/toolbars/DistortableImage.ControlBar.js
src/util/DomUtil.js
src/util/Utils.js

We are getting closer to the stable API and one of the important features
is to allow developers to translate LDI in their native language.
This PR implements the requested feature.
[Demo](https://streamable.com/ahws5)
As you saw in the demo, it displays translations that are provided, but if there are no provided translations it will successfully fall back to English.
This approach is easily extensible since all you have to do when you add a new button/action to the toolbar is to open Utils.js and add a new entry in `translation` object.
Resolves #406
@sashadev-sky @rexagod @jywarren @SidharthBansal it would be great if you could review this :)
Thanks.

ADD: Custom translations functionality

---

README.md
TESTING.md

Testing is described in a new TESTING.md file.
I've also added `grunt test` to the `test` NPM script.
Resolves #506
@cesswairimu could you take a look at this? Thanks.

ADD: Testing documentation

---

dist/leaflet.distortableimage.js
src/edit/DistortableImage.Edit.js

Fixes #383
Part of the "Remove try...catch from _addToolbar" task from Google Code-in (alias: alexberti02).

Remove try...catch from _addToolbar in src/edit/DistortableImage.Edit.js

---

dist/leaflet.distortableimage.js
examples/export.html
package.json
src/edit/DistortableCollection.Edit.js
src/edit/actions/ExportAction.js

Fixes #478 
cc @sashadev-sky @SidharthBansal this is very rough, but I'm making settable options params for all critical export UI and request/response handling; I'm seeing some issue with variable scope, however, so this needs a lot of debugging. I want to demo how setting a custom Exporter and Exporter UI work in the new examples/export.html file, too!
If we can get GCI folks engaged in this, that'd be amazing!

[WIP] customizable export UI for DistortableCollection

---

Gruntfile.js
dist/leaflet.distortableimage.js
package-lock.json
package.json
src/edit/DistortableCollection.Edit.js

[Demo](https://streamable.com/qdzw7)
Resolves #522 
@jywarren @sashadev-sky could you take a look at this? Thanks.

FEATURE: Make collection export option dynamic

---

src/DistortableImageOverlay.js

Fixes #446  
Here is a GIF demonstrating the moving of images at high zoom levels:
Here is a GIF demonstrating that the image still behaves normally when scaled to the size of the map, as noted in issue #402 :
Thanks!

Allow moving of images at high zoom levels

---

package.json
src/edit/DistortableCollection.Edit.js

Thinking this may help https://github.com/publiclab/mapknitter/pull/1192

add opts.resolve to allow stopping export spinner from user-defined functions

---

src/edit/actions/UnlockAction.js

Fixes [#613](https://github.com/publiclab/Leaflet.DistortableImage/issues/613)(<=== Add issue number here)
@sashadev-sky  please review my PR. 
Thanks, interested to change for other files too.

Update L.UnlockAction method creation to ES6 syntax

---

.gitpod.yml

Building on example at https://github.com/publiclab/image-sequencer/pull/1668
cc @sashadev-sky take a look - gitpod can build a full hosted version for each PR!

Try setting up gitpod for building for each PR to ease reviewing

---

.eslintignore
.travis.yml
package-lock.json
package.json
test/karma.conf.js
test/src/edit/DistortableImageEditSpec.js

Fixes #625  (<=== Add issue number here)
Thanks!

Update travis config

---

src/util/TrigUtil.js

Issue-587: update trigUtil method syntax to ES6

---

src/edit/DistortableImage.Edit.js

Updating L.DistortableImage.Edit.js method creation to ES6 syntax III

---

src/components/DistortableImage.Keymapper.js

Fixes #765  (<=== Add issue number here)
Thanks!

changed in DistortableImage.Keymapper- by removing the function

---

dist/leaflet.distortableimage.css
examples/archive.html

chore: 🤖 set up inital map view

---

dist/leaflet.distortableimage.js
src/edit/DistortableImage.Edit.js

Currently, it's possible to listen to `dragend` for draggable edit handles like so:
```js
layer.on('dragend', handleDragEditHandle)
```
There is, however, no way to listen to `dragend` in the event the whole layer is dragged. This PR adds this functionality by firing the layer `dragend` event when the layer's `dragging` property fires its `dragend` event.
Closes #1016
---
Please be sure you've reviewed our contribution guidelines at …

Push dragend event to overlay

---

examples/archive.html

feat: 🎸 display collection's images in sidebar

---

src/mapmixins/DoubleClickLabels.js

Update method creation syntax to ES6 DoubleClickLabels.js
Fixes #1068(<=== Add issue number here)
Thanks!

Update method creation syntax to ES6 DoubleClickLabels.js

---

src/edit/handles/RotateHandle.js

Fixes #1086
* [@TildaDares ] @mention the original creator of the issue in a comment below for help or for a review
Thanks!

Replaced `var` keyword with `const` in RotateHandle.js

---

src/mapmixins/MapMixins.js

Fixes #1086 (MapMixins.js)
I replaced the "var" keywords with "const". Kindly review my pull request and please let me know if there is anything I need to change. Thanks!

replaced var keyword with const

---

src/edit/actions/OpacityAction.js

I changed the var declaration to let/const where necessary
Thanks!

Replace var keyword with let/const

---

dist/leaflet.distortableimage.js
src/components/DistortableImage.Keymapper.js

@TildaDares I have fixed the issues in  ..... Fixes #1086 
[https://github.com/publiclab/Leaflet.DistortableImage/issues/1086](url).
in this directory Leaflet.DistortableImage/src/components/DistortableImage.Keymapper.js 
I changed the variable declaration on line 42 from "var" to const 
I changed the variable declaration on line 45 from "var" to let 
I changed the variable declaration on line 52 from "var" to const 
I changed the variable declaration on line 66 from "var" to const 
I changed the variable declaration on line 131 from "var" to const

changed some variable declarations in Leaflet.DistortableImage/src/components/DistortableImage.Keymapper.js 

---

src/edit/handles/EditHandle.js

Fixes #1086  (<=== Add issue number here)
Thanks!

change var to let or const

---

src/edit/actions/EditAction.js

Updated `var` with `let` or `const` in `src/edit/actions/EditAction.js`
Thanks!

feat(Refactor): Replace `var` with `let`/`const` in EditAction.js

---

src/edit/toolbars/DistortableImage.ControlBar.js

@TildaDares  this is my pull request 
fixes #1086 
Changed var keyword to  const keyword in DistortableImage.ControlBar.js in line 28

Changing var keyword to const

---

examples/archive.html

Displayed url of image origin, in MapKnitter Lite interface

---

examples/js/index.js

Update /examples/js/index.js to include a missing code `L.Control.geocoder().addTo(map);`
Fixes #1212 (<=== Add issue number here)
* [X ] PR is descriptively titled 📑 and links the original issue above 🔗
* [X ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt test`
Thanks!

Update index.js to include missing code

---

test/src/edit/DistortableCollectionEditSpec.js

Fixes #1235
Made sure these boxes are checked before the pull request (PR) is ready to be reviewed and merged.

Change nameless functions to arrow functions

---

Gruntfile.js

Fixes #1253
Hello, sharing the link to code review ==> [link to this PR](https://github.com/krishan-1/Leaflet.DistortableImage)
Thanks!

Changed var keyword to let or const #1253

---

test/src/edit/DistortableImageEditSpec.js

Changed the regular functions to arrow functions
Fixes #1239(<=== Add issue number here)
Thanks!

Changed Regular functions to arrow function

---

Gruntfile.js

convert regular to arrow function

---

dist/leaflet.distortableimage.js
examples/archive.html

Fixes #1272 (<=== Add issue number here)
Hey @jywarren. I have added search feature to archive.html.

Added search location feature to archive.html

---

dist/leaflet.distortableimage.js
examples/archive.html
examples/js/archive.js

Code cleanup in terms of indentation, link, script, and meta spacing and ensuring no code break and maintained functionality.
Thanks!

Clean up archive.html and archive.js

---

examples/js/local.js
examples/local.css
examples/local.html

Based on the review comment here: https://github.com/publiclab/Leaflet.DistortableImage/pull/1293#issuecomment-1351772834
I included a toggle open and close button, with all functionality retained

infoBar toggle

---

debug/pixelorigin.js

Fixes #1160 (<=== Add issue number here)
Thanks!

Rest of the updates (Replacing Var)

---

src/mapmixins/BoxCollector.js

Issue 1311 - change let to const

---

src/edit/DistortableImage.Edit.js

Fixes #1318 
I have updated the document from let to const in src/edit/DistortableImage.Edit.js .
I am sorry for the last comment, please don't mind as I am very new to open source and I was not aware how to write comment, very sorry for this.

Changed let to const in src/edit/DistortableImage.Edit.js

---

src/util/ImageUtil.js

Change Keyword var to let in src/util/ImageUtil.js
Fixes #1307 
Thanks!

Update ImageUtil.js, Fixes Issue #1307

---

dist/leaflet.distortableimage.js
examples/js/archive.js

load image in sidebar as thumbnail 

---

README.md

Fixes #1332
* [✔️ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ✔️] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt test`
* [ ✔️] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ✔️] screenshots/GIFs are attached 📎 in case of UI updates
* [ ✔️] @mention the original creator of the issue in a comment below for help or for a review
Please be sure you've reviewed …

Issue #1332 Updated Document Tooltip Feature in README.md
